services:

  meshpartition-web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    working_dir: /app
    ports:
      - "5050:5000"
    command: ["python", "webapp/app.py"]
